version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./public:/var/www/html/public:ro
    ports:
      - 8888:80
    environment:
      PHP_HOST: app
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - .:/var/www/html:cached
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql:delegated
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_DATABASE: wikieng
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
  selenium:
    build:
      context: .
      dockerfile: docker/selenium/Dockerfile
    ports:
      - '4444:4444'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=example.cw5hony92ugy.ap-northeast-1.rds.amazonaws.com
      - PMA_USER=root
      - PMA_PASSWORD=topsecret
    ports:
      - 8080:80
